import { VideosData } from "@/interfaces/VideoData";

export const videos: VideosData[] = [
  {
    link: "https://example.com/video1",
    title: "Amazing Nature Documentary",
    thubImg: "https://example.com/thumb1.jpg",
    duration: "2:15:30",
    views: 1200000,
    publicationDate: "2022-06-15",
    favorite: true,
  },
  {
    link: "https://example.com/video2",
    title: "Top 10 Coding Tips",
    thubImg: "https://example.com/thumb2.jpg",
    duration: "0:10:45",
    views: 850000,
    publicationDate: "2021-11-22",
    favorite: false,
  },
  {
    link: "https://example.com/video3",
    title: "Epic Space Journey",
    thubImg: "https://example.com/thumb3.jpg",
    duration: "1:30:20",
    views: 1500000,
    publicationDate: "2020-08-10",
    favorite: true,
  },
  {
    link: "https://example.com/video4",
    title: "Beginner Yoga Routine",
    thubImg: "https://example.com/thumb4.jpg",
    duration: "0:25:30",
    views: 900000,
    publicationDate: "2023-01-05",
    favorite: false,
  },
  {
    link: "https://example.com/video5",
    title: "History of Ancient Rome",
    thubImg: "https://example.com/thumb5.jpg",
    duration: "2:00:00",
    views: 700000,
    publicationDate: "2019-04-17",
    favorite: true,
  },
  {
    link: "https://example.com/video6",
    title: "Advanced Python Programming",
    thubImg: "https://example.com/thumb6.jpg",
    duration: "1:45:15",
    views: 650000,
    publicationDate: "2021-05-30",
    favorite: false,
  },
  {
    link: "https://example.com/video7",
    title: "Mastering Public Speaking",
    thubImg: "https://example.com/thumb7.jpg",
    duration: "0:55:20",
    views: 500000,
    publicationDate: "2022-09-25",
    favorite: true,
  },
  {
    link: "https://example.com/video8",
    title: "Guitar Lessons for Beginners",
    thubImg: "https://example.com/thumb8.jpg",
    duration: "1:10:45",
    views: 300000,
    publicationDate: "2020-12-12",
    favorite: false,
  },
  {
    link: "https://example.com/video9",
    title: "Travel Vlog: Japan",
    thubImg: "https://example.com/thumb9.jpg",
    duration: "0:45:00",
    views: 2000000,
    publicationDate: "2018-07-20",
    favorite: true,
  },
  {
    link: "https://example.com/video10",
    title: "Cooking Masterclass",
    thubImg: "https://example.com/thumb10.jpg",
    duration: "1:35:10",
    views: 1200000,
    publicationDate: "2021-03-14",
    favorite: false,
  },
  {
    link: "https://example.com/video11",
    title: "Fitness Bootcamp",
    thubImg: "https://example.com/thumb11.jpg",
    duration: "0:40:30",
    views: 450000,
    publicationDate: "2019-11-05",
    favorite: true,
  },
  {
    link: "https://example.com/video12",
    title: "Meditation for Beginners",
    thubImg: "https://example.com/thumb12.jpg",
    duration: "0:30:15",
    views: 800000,
    publicationDate: "2023-02-22",
    favorite: false,
  },
  {
    link: "https://example.com/video13",
    title: "Photography Tips & Tricks",
    thubImg: "https://example.com/thumb13.jpg",
    duration: "1:20:45",
    views: 900000,
    publicationDate: "2020-05-19",
    favorite: true,
  },
  {
    link: "https://example.com/video14",
    title: "Building a PC",
    thubImg: "https://example.com/thumb14.jpg",
    duration: "2:05:30",
    views: 750000,
    publicationDate: "2021-07-03",
    favorite: false,
  },
  {
    link: "https://example.com/video15",
    title: "Wildlife Safari",
    thubImg: "https://example.com/thumb15.jpg",
    duration: "1:50:20",
    views: 1000000,
    publicationDate: "2018-10-15",
    favorite: true,
  },
  {
    link: "https://example.com/video16",
    title: "Learning Spanish",
    thubImg: "https://example.com/thumb16.jpg",
    duration: "0:35:40",
    views: 600000,
    publicationDate: "2019-02-27",
    favorite: false,
  },
  {
    link: "https://example.com/video17",
    title: "Exploring the Ocean Depths",
    thubImg: "https://example.com/thumb17.jpg",
    duration: "1:15:00",
    views: 1100000,
    publicationDate: "2022-11-10",
    favorite: true,
  },
  {
    link: "https://example.com/video18",
    title: "Basics of Drawing",
    thubImg: "https://example.com/thumb18.jpg",
    duration: "0:50:25",
    views: 400000,
    publicationDate: "2023-04-08",
    favorite: false,
  },
  {
    link: "https://example.com/video19",
    title: "Secrets of the Universe",
    thubImg: "https://example.com/thumb19.jpg",
    duration: "2:25:35",
    views: 1400000,
    publicationDate: "2020-06-21",
    favorite: true,
  },
  {
    link: "https://example.com/video20",
    title: "Virtual Reality Explained",
    thubImg: "https://example.com/thumb20.jpg",
    duration: "1:05:50",
    views: 500000,
    publicationDate: "2021-08-30",
    favorite: false,
  },
];
